language: go
services:
- docker
matrix:
  include:
  - go: 1.10.x
    script: make test
  - go: 1.11.x
    script: make test
  - go: 1.11.x
    script: make build-docker
  - language: python
    python: '3.6'
    script:
    - pip install pipenv
    - cd clients/py
    - pipenv sync --dev
    - pipenv run python -m pytest -v
  - language: python
    python: 3.7-dev
    env:
    - PATH=/opt/go/bin:${PATH}
    - GOROOT=/opt/go
    before_install:
    - curl -LO https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
    - tar xzf go1.11.1.linux-amd64.tar.gz -C /opt
    script:
    - pip install pipenv
    - cd clients/py
    - pipenv sync --dev
    - pipenv run python -m pytest -v
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: NwON2F5YhpSHt326DNkLA4lTtb+BFS2XXaH1XyofBRHwuI2xY6WO+6tEn15Kp9Ccm/EoBy2bScy2WBmYD/DsP4KIJOuL2XtRf2ld81FsFsbaUD0uBJJY4gDP5iYyq3fqvssf8oVLUdVerJpyG+98ZlU6ae2o0KAbfUTr6hr7DgjJ8azZMVx8j2IWFcy1S9Db4KmAI0zni+d4v3BGV0VWsDfzOa3CiFb4hVQvBxMuw5Nwtn2PpVkvoYnDM2o0oQFk38ggngvc0Ox4qNxmND0hnxveb9YZ8c69ieHuvaYSLb+3BpI99fonVhLd5LetyuTL/qaQjnnkeC87I6f9QLdCiQwBT56FJShxsPgGtmDdNAel9IbKGrEUi5RR4NQKbQvd8U4LElor0wxK9PryXpRWbNb15WG9db/jjFjylgvTlcVs6Evz3EWReDtAa/dDSIr0Swn3nNV0sQps/9zqWMkFTPOiYlId1DNqw6x31YRIKrJKzWbDCj6C8ukWjPrCjGPMiZTt5srZUCoV07Gzw71/b8JaeqQMhPC4OlQuR+nIhvDZNdM1ADJ/5MCowdGhYwQf45npo+XHeTwHMJqydpXkJi3i5pbhE7iE02Z89mgsB114B4RDzOOOOwuKGPSsgOTBlFA2dZLHCKClTXWOEAm+OT3dXl0PMtR9Upz8mr59+EU=
install: true
