language: go

services:
  - docker

matrix:
  include:
  - go: "1.10.x"
    script:  make test
  - go: "1.11.x"
    script: make test
  - go: "1.11.x"
    script: make build-docker
  - language: python
    python: "3.6"
    script:
      - make travis-py
  - language: python
    python: "3.7-dev"
    script:
      - make travis-py

env:
  - GO111MODULE=on

install: true
