[log]
level = "info"

[[backends]]
name = "weather"
type = "csv"
rootDir = "/var/data/weather"

[[backends]]
name = "v3io"
type = "kv"
v3ioURL = "http://v3.io"
container = "a"
path = "/data"
username = "daffy"
password = "duck"
workers = 2
